export const PluginMessageEnum = {
  SUBMIT: 'SUBMIT',
  SELECTED_SVGS: 'SELECTED_SVGS',
  SAVE_ICONFONT: 'SAVE_ICONFONT',
  CHECK_VALUE: 'CHECK_VALUE',
  CHECKED_VALUE: 'CHECKED_VALUE',
} as const;

export const UNICODE = 0xea01;
